### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration

### ISSUE THREAD

**Issue by lon9man** [smithy-lang/smithy-kotlin#1189]
### Describe the bug

got error

```
D  Delegated worker class com.appname.data.worker.upload.UploadWorker threw exception in startWork.
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;
at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngineKt.buildClientFromConfig(OkHttpEngine.kt:98)
at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngineKt.buildClientWithConnectionListener(OkHttpEngine.kt:159)
at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngineKt.access$buildClientWithConnectionListener(OkHttpEngine.kt:1)
at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:48)
at aws.smithy.kotlin.runtime.http.engine.okhttp.OkHttpEngine$Companion.invoke(OkHttpEngine.kt:41)
at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineJVMKt.newDefaultHttpEngine(DefaultHttpEngineJVM.kt:14)
at aws.smithy.kotlin.runtime.http.engine.DefaultHttpEngineKt.DefaultHttpEngine(DefaultHttpEngine.kt:24)
at aws.smithy.kotlin.runtime.http.engine.HttpEngineConfigImpl$BuilderImpl$engineConstructor$1.invoke(HttpEngineConfigImpl.kt:20)
at aws.smithy.kotlin.runtime.http.engine.HttpEngineConfigImpl$BuilderImpl$engineConstructor$1.invoke(HttpEngineConfigImpl.kt:20)
at aws.smithy.kotlin.runtime.http.engine.HttpEngineConfigImpl$BuilderImpl.engineSupplier$lambda$2(HttpEngineConfigImpl.kt:21)
at aws.smithy.kotlin.runtime.http.engine.HttpEngineConfigImpl$BuilderImpl.$r8$lambda$FxDGT4mi-_cG_55NQVyO8SbpKzQ(HttpEngineConfigImpl.kt)
at aws.smithy.kotlin.runtime.http.engine.HttpEngineConfigImpl$BuilderImpl$$ExternalSyntheticLambda7.invoke(D8$$SyntheticClass:0)
at aws.smithy.kotlin.runtime.http.engine.HttpEngineConfigImpl$BuilderImpl.buildHttpEngineConfig(HttpEngineConfigImpl.kt:77)
at aws.sdk.kotlin.services.s3.S3Client$Config$Builder.buildHttpEngineConfig(S3Client.kt)
at aws.sdk.kotlin.services.s3.S3Client$Config.<init>(S3Client.kt:281)
at aws.sdk.kotlin.services.s3.S3Client$Config.<init>(S3Client.kt)
at aws.sdk.kotlin.services.s3.S3Client$Config$Builder.build(S3Client.kt:499)
at aws.sdk.kotlin.services.s3.S3Client$Config$Builder.build(S3Client.kt:337)
at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:20)
at aws.smithy.kotlin.runtime.client.AbstractSdkClientBuilder.build(AbstractSdkClientBuilder.kt:13)
at aws.smithy.kotlin.runtime.client.AbstractSdkClientFactory.invoke(AbstractSdkClientFactory.kt:22)
at com.appname.data.di.DataDi.provideS3Client(DataDi.kt:174)
at com.appname.data.di.DataDi_ProvideS3ClientFactory.provideS3Client(DataDi_ProvideS3ClientFactory.java:47)
at com.appname.DaggerAppNameApplication_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerAppNameApplication_HiltComponents_SingletonC.java:1208)
at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
at com.appname.data.worker.upload.UploadWorker$doWork$2.invokeSuspend(UploadWorker.kt:166)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.Duration" on path: DexPathList[[zip file "/data/app/com.appname.dev-2/base.apk"],nativeLibraryDirectories=[/data/app/com.appname.dev-2/lib/x86, /data/app/com.appname.dev-2/base.apk!/lib/x86, /system/lib, /vendor/lib]]
```

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected behavior

no error

### Current behavior

got error `D  Delegated worker class com.appname.data.worker.upload.UploadWorker threw exception in startWork.
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Duration;`

### Steps to Reproduce

run project on Nexus 5 (API 24). 
on creation s3Client - fail occurs
```
val s3Client = S3Client {
            region = REGION
            this.credentialsProvider = credentialsProvider
        }
```

### Smithy-Kotlin version

used aws-sdk-kotlin = 1.3.82

### Platform (JVM/JS/Native)

Native

### Operating system and version

Ubuntu 20.04.5 LTS

**Comment by lauzadis** [comment]
`java.time.Duration` should be available [through API desugaring](https://developer.android.com/studio/write/java8-support-table), have you configured that for your app? We can update the `OkHttpEngine.buildClientFromConfig` to avoid using `Duration`, but it's also used by `InstantJVM`, which we can't avoid.

**Comment by lon9man** [comment]
@lauzadis thanks for the response. 
added desugaring options. it seems helped
